/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.parser;

import node.*;
import sarapatel.analysis.AnalysisAdapter;
import sarapatel.node.EOF;
import sarapatel.node.TAtribuicao;
import sarapatel.node.TCadeia;
import sarapatel.node.TColDir;
import sarapatel.node.TColEsq;
import sarapatel.node.TConst;
import sarapatel.node.TDecimal;
import sarapatel.node.TDiv;
import sarapatel.node.TDoisPontos;
import sarapatel.node.TE;
import sarapatel.node.TEnquanto;
import sarapatel.node.TFalso;
import sarapatel.node.TFimBloco;
import sarapatel.node.TFuncao;
import sarapatel.node.TId;
import sarapatel.node.TIgual;
import sarapatel.node.TIniBloco;
import sarapatel.node.TMaiorIgual;
import sarapatel.node.TMaiorQ;
import sarapatel.node.TMenos;
import sarapatel.node.TMod;
import sarapatel.node.TMult;
import sarapatel.node.TNao;
import sarapatel.node.TNumero;
import sarapatel.node.TOu;
import sarapatel.node.TParDir;
import sarapatel.node.TParEsq;
import sarapatel.node.TPontoVirgula;
import sarapatel.node.TProcedPrincipal;
import sarapatel.node.TProcedimento;
import sarapatel.node.TSe;
import sarapatel.node.TSenao;
import sarapatel.node.TSeparador;
import sarapatel.node.TSoma;
import sarapatel.node.TTipoArray;
import sarapatel.node.TTipoBooleano;
import sarapatel.node.TTipoCadeia;
import sarapatel.node.TTipoInteiro;
import sarapatel.node.TTipoReal;
import sarapatel.node.TVar;
import sarapatel.node.TVerdadeiro;
import analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 0;
    }

    @Override
    public void caseTDecimal(@SuppressWarnings("unused") TDecimal node)
    {
        this.index = 1;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 2;
    }

    @Override
    public void caseTColEsq(@SuppressWarnings("unused") TColEsq node)
    {
        this.index = 3;
    }

    @Override
    public void caseTColDir(@SuppressWarnings("unused") TColDir node)
    {
        this.index = 4;
    }

    @Override
    public void caseTParEsq(@SuppressWarnings("unused") TParEsq node)
    {
        this.index = 5;
    }

    @Override
    public void caseTParDir(@SuppressWarnings("unused") TParDir node)
    {
        this.index = 6;
    }

    @Override
    public void caseTSoma(@SuppressWarnings("unused") TSoma node)
    {
        this.index = 7;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 8;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 9;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 10;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 11;
    }

    @Override
    public void caseTMaiorQ(@SuppressWarnings("unused") TMaiorQ node)
    {
        this.index = 12;
    }

    @Override
    public void caseTMaiorIgual(@SuppressWarnings("unused") TMaiorIgual node)
    {
        this.index = 13;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 14;
    }

    @Override
    public void caseTE(@SuppressWarnings("unused") TE node)
    {
        this.index = 15;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 16;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 17;
    }

    @Override
    public void caseTSeparador(@SuppressWarnings("unused") TSeparador node)
    {
        this.index = 18;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 19;
    }

    @Override
    public void caseTAtribuicao(@SuppressWarnings("unused") TAtribuicao node)
    {
        this.index = 20;
    }

    @Override
    public void caseTProcedPrincipal(@SuppressWarnings("unused") TProcedPrincipal node)
    {
        this.index = 21;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 22;
    }

    @Override
    public void caseTConst(@SuppressWarnings("unused") TConst node)
    {
        this.index = 23;
    }

    @Override
    public void caseTTipoInteiro(@SuppressWarnings("unused") TTipoInteiro node)
    {
        this.index = 24;
    }

    @Override
    public void caseTTipoReal(@SuppressWarnings("unused") TTipoReal node)
    {
        this.index = 25;
    }

    @Override
    public void caseTTipoBooleano(@SuppressWarnings("unused") TTipoBooleano node)
    {
        this.index = 26;
    }

    @Override
    public void caseTTipoCadeia(@SuppressWarnings("unused") TTipoCadeia node)
    {
        this.index = 27;
    }

    @Override
    public void caseTIniBloco(@SuppressWarnings("unused") TIniBloco node)
    {
        this.index = 28;
    }

    @Override
    public void caseTFimBloco(@SuppressWarnings("unused") TFimBloco node)
    {
        this.index = 29;
    }

    @Override
    public void caseTEnquanto(@SuppressWarnings("unused") TEnquanto node)
    {
        this.index = 30;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 31;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 32;
    }

    @Override
    public void caseTVerdadeiro(@SuppressWarnings("unused") TVerdadeiro node)
    {
        this.index = 33;
    }

    @Override
    public void caseTFalso(@SuppressWarnings("unused") TFalso node)
    {
        this.index = 34;
    }

    @Override
    public void caseTFuncao(@SuppressWarnings("unused") TFuncao node)
    {
        this.index = 35;
    }

    @Override
    public void caseTProcedimento(@SuppressWarnings("unused") TProcedimento node)
    {
        this.index = 36;
    }

    @Override
    public void caseTTipoArray(@SuppressWarnings("unused") TTipoArray node)
    {
        this.index = 37;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 38;
    }

    @Override
    public void caseTCadeia(@SuppressWarnings("unused") TCadeia node)
    {
        this.index = 39;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 40;
    }
}
