/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import lexer.*;
import node.*;
import analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PPrograma node1 = (PPrograma) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AAprograma1Programa */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AAprograma2Programa */
            {
                ArrayList<Object> list = new1();
                push(goTo(0), list, false);
            }
            break;
            case 2: /* reduce ADecVarDecsVarConst */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce ADecConsDecsVarConst */
            {
                ArrayList<Object> list = new3();
                push(goTo(1), list, false);
            }
            break;
            case 4: /* reduce ADecProcedimentoDecsProcFunc */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list, false);
            }
            break;
            case 5: /* reduce ADecFuncaoDecsProcFunc */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list, false);
            }
            break;
            case 6: /* reduce ADecCons */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list, false);
            }
            break;
            case 7: /* reduce ADecVar */
            {
                ArrayList<Object> list = new7();
                push(goTo(4), list, false);
            }
            break;
            case 8: /* reduce AIdIds */
            {
                ArrayList<Object> list = new8();
                push(goTo(5), list, false);
            }
            break;
            case 9: /* reduce AIdAtribuicaoIds */
            {
                ArrayList<Object> list = new9();
                push(goTo(5), list, false);
            }
            break;
            case 10: /* reduce ATipoBaseTipo */
            {
                ArrayList<Object> list = new10();
                push(goTo(6), list, false);
            }
            break;
            case 11: /* reduce ATipoArrTipo */
            {
                ArrayList<Object> list = new11();
                push(goTo(6), list, false);
            }
            break;
            case 12: /* reduce ATipoInteiroTipoBase */
            {
                ArrayList<Object> list = new12();
                push(goTo(7), list, false);
            }
            break;
            case 13: /* reduce ATipoBooleanoTipoBase */
            {
                ArrayList<Object> list = new13();
                push(goTo(7), list, false);
            }
            break;
            case 14: /* reduce ATipoRealTipoBase */
            {
                ArrayList<Object> list = new14();
                push(goTo(7), list, false);
            }
            break;
            case 15: /* reduce ATipoCadeiaTipoBase */
            {
                ArrayList<Object> list = new15();
                push(goTo(7), list, false);
            }
            break;
            case 16: /* reduce AIdAtribuicao */
            {
                ArrayList<Object> list = new16();
                push(goTo(8), list, false);
            }
            break;
            case 17: /* reduce AArrayComp */
            {
                ArrayList<Object> list = new17();
                push(goTo(9), list, false);
            }
            break;
            case 18: /* reduce AAdecprocedimento1DecProcedimento */
            {
                ArrayList<Object> list = new18();
                push(goTo(10), list, false);
            }
            break;
            case 19: /* reduce AAdecprocedimento2DecProcedimento */
            {
                ArrayList<Object> list = new19();
                push(goTo(10), list, false);
            }
            break;
            case 20: /* reduce ADecFuncao */
            {
                ArrayList<Object> list = new20();
                push(goTo(11), list, false);
            }
            break;
            case 21: /* reduce AParametros */
            {
                ArrayList<Object> list = new21();
                push(goTo(12), list, false);
            }
            break;
            case 22: /* reduce AParametroSeparadorParametroSeparadorParametroVazio */
            {
                ArrayList<Object> list = new22();
                push(goTo(13), list, false);
            }
            break;
            case 23: /* reduce AVazioSeparadorParametroVazio */
            {
                ArrayList<Object> list = new23();
                push(goTo(13), list, false);
            }
            break;
            case 24: /* reduce AAparametroseparadorparametro1ParametroSeparadorParametro */
            {
                ArrayList<Object> list = new24();
                push(goTo(14), list, false);
            }
            break;
            case 25: /* reduce AAparametroseparadorparametro2ParametroSeparadorParametro */
            {
                ArrayList<Object> list = new25();
                push(goTo(14), list, false);
            }
            break;
            case 26: /* reduce ASeparadorParametro */
            {
                ArrayList<Object> list = new26();
                push(goTo(15), list, false);
            }
            break;
            case 27: /* reduce AParametro */
            {
                ArrayList<Object> list = new27();
                push(goTo(16), list, false);
            }
            break;
            case 28: /* reduce ATipoBaseTipoParametro */
            {
                ArrayList<Object> list = new28();
                push(goTo(17), list, false);
            }
            break;
            case 29: /* reduce ATipoParametroTipoParametro */
            {
                ArrayList<Object> list = new29();
                push(goTo(17), list, false);
            }
            break;
            case 30: /* reduce AIdIdExp */
            {
                ArrayList<Object> list = new30();
                push(goTo(18), list, false);
            }
            break;
            case 31: /* reduce AExpIdExp */
            {
                ArrayList<Object> list = new31();
                push(goTo(18), list, false);
            }
            break;
            case 32: /* reduce AIdValor */
            {
                ArrayList<Object> list = new32();
                push(goTo(19), list, false);
            }
            break;
            case 33: /* reduce AValorValor */
            {
                ArrayList<Object> list = new33();
                push(goTo(19), list, false);
            }
            break;
            case 34: /* reduce AChamadaFuncao */
            {
                ArrayList<Object> list = new34();
                push(goTo(20), list, false);
            }
            break;
            case 35: /* reduce AChamadaProcedimento */
            {
                ArrayList<Object> list = new35();
                push(goTo(21), list, false);
            }
            break;
            case 36: /* reduce AAexpinilistaexp1ListaExp */
            {
                ArrayList<Object> list = new36();
                push(goTo(22), list, false);
            }
            break;
            case 37: /* reduce AAexpinilistaexp2ListaExp */
            {
                ArrayList<Object> list = new37();
                push(goTo(22), list, false);
            }
            break;
            case 38: /* reduce AVazioListaExp */
            {
                ArrayList<Object> list = new38();
                push(goTo(22), list, false);
            }
            break;
            case 39: /* reduce ASeparadorExp */
            {
                ArrayList<Object> list = new39();
                push(goTo(23), list, false);
            }
            break;
            case 40: /* reduce AAblocoexpressoes1BlocoExpressoes */
            {
                ArrayList<Object> list = new40();
                push(goTo(24), list, false);
            }
            break;
            case 41: /* reduce AAblocoexpressoes2BlocoExpressoes */
            {
                ArrayList<Object> list = new41();
                push(goTo(24), list, false);
            }
            break;
            case 42: /* reduce AFatorExp */
            {
                ArrayList<Object> list = new42();
                push(goTo(25), list, false);
            }
            break;
            case 43: /* reduce ASomaExp */
            {
                ArrayList<Object> list = new43();
                push(goTo(25), list, false);
            }
            break;
            case 44: /* reduce AMenosExp */
            {
                ArrayList<Object> list = new44();
                push(goTo(25), list, false);
            }
            break;
            case 45: /* reduce ATermoFator */
            {
                ArrayList<Object> list = new45();
                push(goTo(26), list, false);
            }
            break;
            case 46: /* reduce AMultFator */
            {
                ArrayList<Object> list = new46();
                push(goTo(26), list, false);
            }
            break;
            case 47: /* reduce ADivFator */
            {
                ArrayList<Object> list = new47();
                push(goTo(26), list, false);
            }
            break;
            case 48: /* reduce AModFator */
            {
                ArrayList<Object> list = new48();
                push(goTo(26), list, false);
            }
            break;
            case 49: /* reduce ANumeroTermo */
            {
                ArrayList<Object> list = new49();
                push(goTo(27), list, false);
            }
            break;
            case 50: /* reduce AExpTermo */
            {
                ArrayList<Object> list = new50();
                push(goTo(27), list, false);
            }
            break;
            case 51: /* reduce ATerminal$DecsProcFunc */
            {
                ArrayList<Object> list = new51();
                push(goTo(28), list, true);
            }
            break;
            case 52: /* reduce ANonTerminal$DecsProcFunc */
            {
                ArrayList<Object> list = new52();
                push(goTo(28), list, true);
            }
            break;
            case 53: /* reduce ATerminal$DecsVarConst */
            {
                ArrayList<Object> list = new53();
                push(goTo(29), list, true);
            }
            break;
            case 54: /* reduce ANonTerminal$DecsVarConst */
            {
                ArrayList<Object> list = new54();
                push(goTo(29), list, true);
            }
            break;
            case 55: /* reduce ATerminal$SeparadorParametro */
            {
                ArrayList<Object> list = new55();
                push(goTo(30), list, true);
            }
            break;
            case 56: /* reduce ANonTerminal$SeparadorParametro */
            {
                ArrayList<Object> list = new56();
                push(goTo(30), list, true);
            }
            break;
            case 57: /* reduce ATerminal$SeparadorExp */
            {
                ArrayList<Object> list = new57();
                push(goTo(31), list, true);
            }
            break;
            case 58: /* reduce ANonTerminal$SeparadorExp */
            {
                ArrayList<Object> list = new58();
                push(goTo(31), list, true);
            }
            break;
            case 59: /* reduce ATerminal$DecCons */
            {
                ArrayList<Object> list = new59();
                push(goTo(32), list, true);
            }
            break;
            case 60: /* reduce ANonTerminal$DecCons */
            {
                ArrayList<Object> list = new60();
                push(goTo(32), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AAprograma1Programa */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        {
            // Block
        }
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList1.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pprogramaNode1 = new APrograma(listNode2, listNode4);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAprograma2Programa */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pprogramaNode1 = new APrograma(listNode3, listNode5);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce ADecVarDecsVarConst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecsVarConst pdecsvarconstNode1;
        {
            // Block
        PDecVar pdecvarNode2;
        pdecvarNode2 = (PDecVar)nodeArrayList1.get(0);

        pdecsvarconstNode1 = new ADecVarDecsVarConst(pdecvarNode2);
        }
	nodeList.add(pdecsvarconstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce ADecConsDecsVarConst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecsVarConst pdecsvarconstNode1;
        {
            // Block
        PDecCons pdecconsNode2;
        pdecconsNode2 = (PDecCons)nodeArrayList1.get(0);

        pdecsvarconstNode1 = new ADecConsDecsVarConst(pdecconsNode2);
        }
	nodeList.add(pdecsvarconstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce ADecProcedimentoDecsProcFunc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecsProcFunc pdecsprocfuncNode1;
        {
            // Block
        PDecProcedimento pdecprocedimentoNode2;
        pdecprocedimentoNode2 = (PDecProcedimento)nodeArrayList1.get(0);

        pdecsprocfuncNode1 = new ADecProcedimentoDecsProcFunc(pdecprocedimentoNode2);
        }
	nodeList.add(pdecsprocfuncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ADecFuncaoDecsProcFunc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecsProcFunc pdecsprocfuncNode1;
        {
            // Block
        PDecFuncao pdecfuncaoNode2;
        pdecfuncaoNode2 = (PDecFuncao)nodeArrayList1.get(0);

        pdecsprocfuncNode1 = new ADecFuncaoDecsProcFunc(pdecfuncaoNode2);
        }
	nodeList.add(pdecsprocfuncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce ADecCons */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecCons pdecconsNode1;
        {
            // Block
        TConst tconstNode2;
        TDoisPontos tdoispontosNode3;
        PTipo ptipoNode4;
        PIdAtribuicao pidatribuicaoNode5;
        TPontoVirgula tpontovirgulaNode6;
        tconstNode2 = (TConst)nodeArrayList1.get(0);
        tdoispontosNode3 = (TDoisPontos)nodeArrayList2.get(0);
        ptipoNode4 = (PTipo)nodeArrayList3.get(0);
        pidatribuicaoNode5 = (PIdAtribuicao)nodeArrayList4.get(0);
        tpontovirgulaNode6 = (TPontoVirgula)nodeArrayList5.get(0);

        pdecconsNode1 = new ADecCons(tconstNode2, tdoispontosNode3, ptipoNode4, pidatribuicaoNode5, tpontovirgulaNode6);
        }
	nodeList.add(pdecconsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce ADecVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecVar pdecvarNode1;
        {
            // Block
        TVar tvarNode2;
        TDoisPontos tdoispontosNode3;
        PTipo ptipoNode4;
        PIds pidsNode5;
        TPontoVirgula tpontovirgulaNode6;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tdoispontosNode3 = (TDoisPontos)nodeArrayList2.get(0);
        ptipoNode4 = (PTipo)nodeArrayList3.get(0);
        pidsNode5 = (PIds)nodeArrayList4.get(0);
        tpontovirgulaNode6 = (TPontoVirgula)nodeArrayList5.get(0);

        pdecvarNode1 = new ADecVar(tvarNode2, tdoispontosNode3, ptipoNode4, pidsNode5, tpontovirgulaNode6);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AIdIds */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIds pidsNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pidsNode1 = new AIdIds(tidNode2);
        }
	nodeList.add(pidsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AIdAtribuicaoIds */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIds pidsNode1;
        {
            // Block
        PIdAtribuicao pidatribuicaoNode2;
        pidatribuicaoNode2 = (PIdAtribuicao)nodeArrayList1.get(0);

        pidsNode1 = new AIdAtribuicaoIds(pidatribuicaoNode2);
        }
	nodeList.add(pidsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ATipoBaseTipo */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipo ptipoNode1;
        {
            // Block
        PTipoBase ptipobaseNode2;
        ptipobaseNode2 = (PTipoBase)nodeArrayList1.get(0);

        ptipoNode1 = new ATipoBaseTipo(ptipobaseNode2);
        }
	nodeList.add(ptipoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ATipoArrTipo */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipo ptipoNode1;
        {
            // Block
        PTipoBase ptipobaseNode2;
        TColEsq tcolesqNode3;
        PExp pexpNode4;
        TColDir tcoldirNode5;
        ptipobaseNode2 = (PTipoBase)nodeArrayList1.get(0);
        tcolesqNode3 = (TColEsq)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tcoldirNode5 = (TColDir)nodeArrayList4.get(0);

        ptipoNode1 = new ATipoArrTipo(ptipobaseNode2, tcolesqNode3, pexpNode4, tcoldirNode5);
        }
	nodeList.add(ptipoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce ATipoInteiroTipoBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoBase ptipobaseNode1;
        {
            // Block
        TTipoInteiro ttipointeiroNode2;
        ttipointeiroNode2 = (TTipoInteiro)nodeArrayList1.get(0);

        ptipobaseNode1 = new ATipoInteiroTipoBase(ttipointeiroNode2);
        }
	nodeList.add(ptipobaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ATipoBooleanoTipoBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoBase ptipobaseNode1;
        {
            // Block
        TTipoBooleano ttipobooleanoNode2;
        ttipobooleanoNode2 = (TTipoBooleano)nodeArrayList1.get(0);

        ptipobaseNode1 = new ATipoBooleanoTipoBase(ttipobooleanoNode2);
        }
	nodeList.add(ptipobaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce ATipoRealTipoBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoBase ptipobaseNode1;
        {
            // Block
        TTipoReal ttiporealNode2;
        ttiporealNode2 = (TTipoReal)nodeArrayList1.get(0);

        ptipobaseNode1 = new ATipoRealTipoBase(ttiporealNode2);
        }
	nodeList.add(ptipobaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce ATipoCadeiaTipoBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoBase ptipobaseNode1;
        {
            // Block
        TTipoCadeia ttipocadeiaNode2;
        ttipocadeiaNode2 = (TTipoCadeia)nodeArrayList1.get(0);

        ptipobaseNode1 = new ATipoCadeiaTipoBase(ttipocadeiaNode2);
        }
	nodeList.add(ptipobaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce AIdAtribuicao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIdAtribuicao pidatribuicaoNode1;
        {
            // Block
        TId tidNode2;
        TAtribuicao tatribuicaoNode3;
        PExp pexpNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tatribuicaoNode3 = (TAtribuicao)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pidatribuicaoNode1 = new AIdAtribuicao(tidNode2, tatribuicaoNode3, pexpNode4);
        }
	nodeList.add(pidatribuicaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AArrayComp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArrayComp parraycompNode1;
        {
            // Block
        TColEsq tcolesqNode2;
        PIdExp pidexpNode3;
        TColDir tcoldirNode4;
        tcolesqNode2 = (TColEsq)nodeArrayList1.get(0);
        pidexpNode3 = (PIdExp)nodeArrayList2.get(0);
        tcoldirNode4 = (TColDir)nodeArrayList3.get(0);

        parraycompNode1 = new AArrayComp(tcolesqNode2, pidexpNode3, tcoldirNode4);
        }
	nodeList.add(parraycompNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce AAdecprocedimento1DecProcedimento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecProcedimento pdecprocedimentoNode1;
        {
            // Block
        @SuppressWarnings("unused") Object nullNode2 = null;
        TProcedimento tprocedimentoNode3;
        TDoisPontos tdoispontosNode4;
        TId tidNode5;
        TParEsq tparesqNode6;
        PParametros pparametrosNode7;
        TParDir tpardirNode8;
        tprocedimentoNode3 = (TProcedimento)nodeArrayList1.get(0);
        tdoispontosNode4 = (TDoisPontos)nodeArrayList2.get(0);
        tidNode5 = (TId)nodeArrayList3.get(0);
        tparesqNode6 = (TParEsq)nodeArrayList4.get(0);
        pparametrosNode7 = (PParametros)nodeArrayList5.get(0);
        tpardirNode8 = (TParDir)nodeArrayList6.get(0);

        pdecprocedimentoNode1 = new ADecProcedimento(null, tprocedimentoNode3, tdoispontosNode4, tidNode5, tparesqNode6, pparametrosNode7, tpardirNode8);
        }
	nodeList.add(pdecprocedimentoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce AAdecprocedimento2DecProcedimento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecProcedimento pdecprocedimentoNode1;
        {
            // Block
        TProcedPrincipal tprocedprincipalNode2;
        TProcedimento tprocedimentoNode3;
        TDoisPontos tdoispontosNode4;
        TId tidNode5;
        TParEsq tparesqNode6;
        PParametros pparametrosNode7;
        TParDir tpardirNode8;
        tprocedprincipalNode2 = (TProcedPrincipal)nodeArrayList1.get(0);
        tprocedimentoNode3 = (TProcedimento)nodeArrayList2.get(0);
        tdoispontosNode4 = (TDoisPontos)nodeArrayList3.get(0);
        tidNode5 = (TId)nodeArrayList4.get(0);
        tparesqNode6 = (TParEsq)nodeArrayList5.get(0);
        pparametrosNode7 = (PParametros)nodeArrayList6.get(0);
        tpardirNode8 = (TParDir)nodeArrayList7.get(0);

        pdecprocedimentoNode1 = new ADecProcedimento(tprocedprincipalNode2, tprocedimentoNode3, tdoispontosNode4, tidNode5, tparesqNode6, pparametrosNode7, tpardirNode8);
        }
	nodeList.add(pdecprocedimentoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce ADecFuncao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecFuncao pdecfuncaoNode1;
        {
            // Block
        TFuncao tfuncaoNode2;
        TDoisPontos tdoispontosNode3;
        PTipo ptipoNode4;
        TId tidNode5;
        TParEsq tparesqNode6;
        PParametros pparametrosNode7;
        TParDir tpardirNode8;
        PExp pexpNode9;
        tfuncaoNode2 = (TFuncao)nodeArrayList1.get(0);
        tdoispontosNode3 = (TDoisPontos)nodeArrayList2.get(0);
        ptipoNode4 = (PTipo)nodeArrayList3.get(0);
        tidNode5 = (TId)nodeArrayList4.get(0);
        tparesqNode6 = (TParEsq)nodeArrayList5.get(0);
        pparametrosNode7 = (PParametros)nodeArrayList6.get(0);
        tpardirNode8 = (TParDir)nodeArrayList7.get(0);
        pexpNode9 = (PExp)nodeArrayList8.get(0);

        pdecfuncaoNode1 = new ADecFuncao(tfuncaoNode2, tdoispontosNode3, ptipoNode4, tidNode5, tparesqNode6, pparametrosNode7, tpardirNode8, pexpNode9);
        }
	nodeList.add(pdecfuncaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AParametros */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametros pparametrosNode1;
        {
            // Block
        PSeparadorParametroVazio pseparadorparametrovazioNode2;
        pseparadorparametrovazioNode2 = (PSeparadorParametroVazio)nodeArrayList1.get(0);

        pparametrosNode1 = new AParametros(pseparadorparametrovazioNode2);
        }
	nodeList.add(pparametrosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AParametroSeparadorParametroSeparadorParametroVazio */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSeparadorParametroVazio pseparadorparametrovazioNode1;
        {
            // Block
        PParametroSeparadorParametro pparametroseparadorparametroNode2;
        pparametroseparadorparametroNode2 = (PParametroSeparadorParametro)nodeArrayList1.get(0);

        pseparadorparametrovazioNode1 = new AParametroSeparadorParametroSeparadorParametroVazio(pparametroseparadorparametroNode2);
        }
	nodeList.add(pseparadorparametrovazioNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AVazioSeparadorParametroVazio */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PSeparadorParametroVazio pseparadorparametrovazioNode1;
        {
            // Block

        pseparadorparametrovazioNode1 = new AVazioSeparadorParametroVazio();
        }
	nodeList.add(pseparadorparametrovazioNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce AAparametroseparadorparametro1ParametroSeparadorParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametroSeparadorParametro pparametroseparadorparametroNode1;
        {
            // Block
        PParametro pparametroNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        pparametroNode2 = (PParametro)nodeArrayList1.get(0);
        {
            // Block
        }

        pparametroseparadorparametroNode1 = new AParametroSeparadorParametro(pparametroNode2, listNode3);
        }
	nodeList.add(pparametroseparadorparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AAparametroseparadorparametro2ParametroSeparadorParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametroSeparadorParametro pparametroseparadorparametroNode1;
        {
            // Block
        PParametro pparametroNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        pparametroNode2 = (PParametro)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pparametroseparadorparametroNode1 = new AParametroSeparadorParametro(pparametroNode2, listNode4);
        }
	nodeList.add(pparametroseparadorparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce ASeparadorParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSeparadorParametro pseparadorparametroNode1;
        {
            // Block
        TSeparador tseparadorNode2;
        PParametro pparametroNode3;
        tseparadorNode2 = (TSeparador)nodeArrayList1.get(0);
        pparametroNode3 = (PParametro)nodeArrayList2.get(0);

        pseparadorparametroNode1 = new ASeparadorParametro(tseparadorNode2, pparametroNode3);
        }
	nodeList.add(pseparadorparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametro pparametroNode1;
        {
            // Block
        PTipoParametro ptipoparametroNode2;
        TId tidNode3;
        ptipoparametroNode2 = (PTipoParametro)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pparametroNode1 = new AParametro(ptipoparametroNode2, tidNode3);
        }
	nodeList.add(pparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce ATipoBaseTipoParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoParametro ptipoparametroNode1;
        {
            // Block
        PTipoBase ptipobaseNode2;
        ptipobaseNode2 = (PTipoBase)nodeArrayList1.get(0);

        ptipoparametroNode1 = new ATipoBaseTipoParametro(ptipobaseNode2);
        }
	nodeList.add(ptipoparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce ATipoParametroTipoParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoParametro ptipoparametroNode1;
        {
            // Block
        PTipoParametro ptipoparametroNode2;
        TColEsq tcolesqNode3;
        TColDir tcoldirNode4;
        ptipoparametroNode2 = (PTipoParametro)nodeArrayList1.get(0);
        tcolesqNode3 = (TColEsq)nodeArrayList2.get(0);
        tcoldirNode4 = (TColDir)nodeArrayList3.get(0);

        ptipoparametroNode1 = new ATipoParametroTipoParametro(ptipoparametroNode2, tcolesqNode3, tcoldirNode4);
        }
	nodeList.add(ptipoparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce AIdIdExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIdExp pidexpNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pidexpNode1 = new AIdIdExp(tidNode2);
        }
	nodeList.add(pidexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AExpIdExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIdExp pidexpNode1;
        {
            // Block
        PExp pexpNode2;
        pexpNode2 = (PExp)nodeArrayList1.get(0);

        pidexpNode1 = new AExpIdExp(pexpNode2);
        }
	nodeList.add(pidexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AIdValor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PValor pvalorNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pvalorNode1 = new AIdValor(tidNode2);
        }
	nodeList.add(pvalorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AValorValor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PValor pvalorNode1;
        {
            // Block
        PValor pvalorNode2;
        TColEsq tcolesqNode3;
        PExp pexpNode4;
        TColDir tcoldirNode5;
        pvalorNode2 = (PValor)nodeArrayList1.get(0);
        tcolesqNode3 = (TColEsq)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tcoldirNode5 = (TColDir)nodeArrayList4.get(0);

        pvalorNode1 = new AValorValor(pvalorNode2, tcolesqNode3, pexpNode4, tcoldirNode5);
        }
	nodeList.add(pvalorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AChamadaFuncao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PChamadaFuncao pchamadafuncaoNode1;
        {
            // Block
        TId tidNode2;
        TParEsq tparesqNode3;
        PListaExp plistaexpNode4;
        TParDir tpardirNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tparesqNode3 = (TParEsq)nodeArrayList2.get(0);
        plistaexpNode4 = (PListaExp)nodeArrayList3.get(0);
        tpardirNode5 = (TParDir)nodeArrayList4.get(0);

        pchamadafuncaoNode1 = new AChamadaFuncao(tidNode2, tparesqNode3, plistaexpNode4, tpardirNode5);
        }
	nodeList.add(pchamadafuncaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AChamadaProcedimento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PChamadaProcedimento pchamadaprocedimentoNode1;
        {
            // Block
        TId tidNode2;
        TParEsq tparesqNode3;
        PListaExp plistaexpNode4;
        TParDir tpardirNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tparesqNode3 = (TParEsq)nodeArrayList2.get(0);
        plistaexpNode4 = (PListaExp)nodeArrayList3.get(0);
        tpardirNode5 = (TParDir)nodeArrayList4.get(0);

        pchamadaprocedimentoNode1 = new AChamadaProcedimento(tidNode2, tparesqNode3, plistaexpNode4, tpardirNode5);
        }
	nodeList.add(pchamadaprocedimentoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AAexpinilistaexp1ListaExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListaExp plistaexpNode1;
        {
            // Block
        PExp pexpNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        {
            // Block
        }

        plistaexpNode1 = new AExpIniListaExp(pexpNode2, listNode3);
        }
	nodeList.add(plistaexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce AAexpinilistaexp2ListaExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListaExp plistaexpNode1;
        {
            // Block
        PExp pexpNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        plistaexpNode1 = new AExpIniListaExp(pexpNode2, listNode4);
        }
	nodeList.add(plistaexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AVazioListaExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListaExp plistaexpNode1;
        {
            // Block

        plistaexpNode1 = new AVazioListaExp();
        }
	nodeList.add(plistaexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce ASeparadorExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSeparadorExp pseparadorexpNode1;
        {
            // Block
        TSeparador tseparadorNode2;
        PExp pexpNode3;
        tseparadorNode2 = (TSeparador)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);

        pseparadorexpNode1 = new ASeparadorExp(tseparadorNode2, pexpNode3);
        }
	nodeList.add(pseparadorexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AAblocoexpressoes1BlocoExpressoes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PBlocoExpressoes pblocoexpressoesNode1;
        {
            // Block
        TIniBloco tiniblocoNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        PExp pexpNode4;
        TFimBloco tfimblocoNode5;
        tiniblocoNode2 = (TIniBloco)nodeArrayList1.get(0);
        {
            // Block
        }
        pexpNode4 = (PExp)nodeArrayList2.get(0);
        tfimblocoNode5 = (TFimBloco)nodeArrayList3.get(0);

        pblocoexpressoesNode1 = new ABlocoExpressoes(tiniblocoNode2, listNode3, pexpNode4, tfimblocoNode5);
        }
	nodeList.add(pblocoexpressoesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AAblocoexpressoes2BlocoExpressoes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PBlocoExpressoes pblocoexpressoesNode1;
        {
            // Block
        TIniBloco tiniblocoNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        PExp pexpNode5;
        TFimBloco tfimblocoNode6;
        tiniblocoNode2 = (TIniBloco)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        pexpNode5 = (PExp)nodeArrayList3.get(0);
        tfimblocoNode6 = (TFimBloco)nodeArrayList4.get(0);

        pblocoexpressoesNode1 = new ABlocoExpressoes(tiniblocoNode2, listNode4, pexpNode5, tfimblocoNode6);
        }
	nodeList.add(pblocoexpressoesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce AFatorExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PFator pfatorNode2;
        pfatorNode2 = (PFator)nodeArrayList1.get(0);

        pexpNode1 = new AFatorExp(pfatorNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce ASomaExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TSoma tsomaNode3;
        PFator pfatorNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tsomaNode3 = (TSoma)nodeArrayList2.get(0);
        pfatorNode4 = (PFator)nodeArrayList3.get(0);

        pexpNode1 = new ASomaExp(pexpNode2, tsomaNode3, pfatorNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce AMenosExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TMenos tmenosNode3;
        PFator pfatorNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tmenosNode3 = (TMenos)nodeArrayList2.get(0);
        pfatorNode4 = (PFator)nodeArrayList3.get(0);

        pexpNode1 = new AMenosExp(pexpNode2, tmenosNode3, pfatorNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce ATermoFator */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFator pfatorNode1;
        {
            // Block
        PTermo ptermoNode2;
        ptermoNode2 = (PTermo)nodeArrayList1.get(0);

        pfatorNode1 = new ATermoFator(ptermoNode2);
        }
	nodeList.add(pfatorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce AMultFator */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFator pfatorNode1;
        {
            // Block
        PFator pfatorNode2;
        TMult tmultNode3;
        PTermo ptermoNode4;
        pfatorNode2 = (PFator)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        ptermoNode4 = (PTermo)nodeArrayList3.get(0);

        pfatorNode1 = new AMultFator(pfatorNode2, tmultNode3, ptermoNode4);
        }
	nodeList.add(pfatorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce ADivFator */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFator pfatorNode1;
        {
            // Block
        PFator pfatorNode2;
        TDiv tdivNode3;
        PTermo ptermoNode4;
        pfatorNode2 = (PFator)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        ptermoNode4 = (PTermo)nodeArrayList3.get(0);

        pfatorNode1 = new ADivFator(pfatorNode2, tdivNode3, ptermoNode4);
        }
	nodeList.add(pfatorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce AModFator */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFator pfatorNode1;
        {
            // Block
        PFator pfatorNode2;
        TMod tmodNode3;
        PTermo ptermoNode4;
        pfatorNode2 = (PFator)nodeArrayList1.get(0);
        tmodNode3 = (TMod)nodeArrayList2.get(0);
        ptermoNode4 = (PTermo)nodeArrayList3.get(0);

        pfatorNode1 = new AModFator(pfatorNode2, tmodNode3, ptermoNode4);
        }
	nodeList.add(pfatorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce ANumeroTermo */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTermo ptermoNode1;
        {
            // Block
        TNumero tnumeroNode2;
        tnumeroNode2 = (TNumero)nodeArrayList1.get(0);

        ptermoNode1 = new ANumeroTermo(tnumeroNode2);
        }
	nodeList.add(ptermoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce AExpTermo */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTermo ptermoNode1;
        {
            // Block
        TParEsq tparesqNode2;
        PExp pexpNode3;
        TParDir tpardirNode4;
        tparesqNode2 = (TParEsq)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tpardirNode4 = (TParDir)nodeArrayList3.get(0);

        ptermoNode1 = new AExpTermo(tparesqNode2, pexpNode3, tpardirNode4);
        }
	nodeList.add(ptermoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce ATerminal$DecsProcFunc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PDecsProcFunc pdecsprocfuncNode1;
        pdecsprocfuncNode1 = (PDecsProcFunc)nodeArrayList1.get(0);
	if(pdecsprocfuncNode1 != null)
	{
	  listNode2.add(pdecsprocfuncNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce ANonTerminal$DecsProcFunc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PDecsProcFunc pdecsprocfuncNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pdecsprocfuncNode2 = (PDecsProcFunc)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pdecsprocfuncNode2 != null)
	{
	  listNode3.add(pdecsprocfuncNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce ATerminal$DecsVarConst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PDecsVarConst pdecsvarconstNode1;
        pdecsvarconstNode1 = (PDecsVarConst)nodeArrayList1.get(0);
	if(pdecsvarconstNode1 != null)
	{
	  listNode2.add(pdecsvarconstNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce ANonTerminal$DecsVarConst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PDecsVarConst pdecsvarconstNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pdecsvarconstNode2 = (PDecsVarConst)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pdecsvarconstNode2 != null)
	{
	  listNode3.add(pdecsvarconstNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce ATerminal$SeparadorParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PSeparadorParametro pseparadorparametroNode1;
        pseparadorparametroNode1 = (PSeparadorParametro)nodeArrayList1.get(0);
	if(pseparadorparametroNode1 != null)
	{
	  listNode2.add(pseparadorparametroNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new56() /* reduce ANonTerminal$SeparadorParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PSeparadorParametro pseparadorparametroNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pseparadorparametroNode2 = (PSeparadorParametro)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pseparadorparametroNode2 != null)
	{
	  listNode3.add(pseparadorparametroNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new57() /* reduce ATerminal$SeparadorExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PSeparadorExp pseparadorexpNode1;
        pseparadorexpNode1 = (PSeparadorExp)nodeArrayList1.get(0);
	if(pseparadorexpNode1 != null)
	{
	  listNode2.add(pseparadorexpNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new58() /* reduce ANonTerminal$SeparadorExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PSeparadorExp pseparadorexpNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pseparadorexpNode2 = (PSeparadorExp)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pseparadorexpNode2 != null)
	{
	  listNode3.add(pseparadorexpNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new59() /* reduce ATerminal$DecCons */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PDecCons pdecconsNode1;
        pdecconsNode1 = (PDecCons)nodeArrayList1.get(0);
	if(pdecconsNode1 != null)
	{
	  listNode2.add(pdecconsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new60() /* reduce ANonTerminal$DecCons */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PDecCons pdecconsNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pdecconsNode2 = (PDecCons)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pdecconsNode2 != null)
	{
	  listNode3.add(pdecconsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {21, SHIFT, 1}, {22, SHIFT, 2}, {23, SHIFT, 3}, {35, SHIFT, 4}, {36, SHIFT, 5}, },
			{{-1, ERROR, 1}, {36, SHIFT, 15}, },
			{{-1, ERROR, 2}, {19, SHIFT, 16}, },
			{{-1, ERROR, 3}, {19, SHIFT, 17}, },
			{{-1, ERROR, 4}, {19, SHIFT, 18}, },
			{{-1, ERROR, 5}, {19, SHIFT, 19}, },
			{{-1, ERROR, 6}, {40, ACCEPT, -1}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 0}, {21, SHIFT, 1}, {35, SHIFT, 4}, {36, SHIFT, 5}, },
			{{-1, ERROR, 14}, {21, SHIFT, 1}, {22, SHIFT, 2}, {23, SHIFT, 3}, {35, SHIFT, 4}, {36, SHIFT, 5}, },
			{{-1, ERROR, 15}, {19, SHIFT, 23}, },
			{{-1, ERROR, 16}, {24, SHIFT, 24}, {25, SHIFT, 25}, {26, SHIFT, 26}, {27, SHIFT, 27}, },
			{{-1, ERROR, 17}, {24, SHIFT, 24}, {25, SHIFT, 25}, {26, SHIFT, 26}, {27, SHIFT, 27}, },
			{{-1, ERROR, 18}, {24, SHIFT, 24}, {25, SHIFT, 25}, {26, SHIFT, 26}, {27, SHIFT, 27}, },
			{{-1, ERROR, 19}, {38, SHIFT, 32}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 1}, {21, SHIFT, 1}, {35, SHIFT, 4}, {36, SHIFT, 5}, },
			{{-1, ERROR, 23}, {38, SHIFT, 33}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 28}, {38, SHIFT, 34}, },
			{{-1, REDUCE, 10}, {3, SHIFT, 37}, },
			{{-1, ERROR, 30}, {38, SHIFT, 38}, },
			{{-1, ERROR, 31}, {38, SHIFT, 40}, },
			{{-1, ERROR, 32}, {5, SHIFT, 41}, },
			{{-1, ERROR, 33}, {5, SHIFT, 42}, },
			{{-1, REDUCE, 8}, {20, SHIFT, 43}, },
			{{-1, ERROR, 35}, {2, SHIFT, 44}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 37}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, ERROR, 38}, {20, SHIFT, 43}, },
			{{-1, ERROR, 39}, {2, SHIFT, 50}, },
			{{-1, ERROR, 40}, {5, SHIFT, 51}, },
			{{-1, REDUCE, 23}, {24, SHIFT, 24}, {25, SHIFT, 25}, {26, SHIFT, 26}, {27, SHIFT, 27}, },
			{{-1, REDUCE, 23}, {24, SHIFT, 24}, {25, SHIFT, 25}, {26, SHIFT, 26}, {27, SHIFT, 27}, },
			{{-1, ERROR, 43}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 49}, },
			{{-1, ERROR, 46}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, ERROR, 47}, {4, SHIFT, 61}, {7, SHIFT, 62}, {8, SHIFT, 63}, },
			{{-1, REDUCE, 42}, {9, SHIFT, 64}, {10, SHIFT, 65}, {11, SHIFT, 66}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 23}, {24, SHIFT, 24}, {25, SHIFT, 25}, {26, SHIFT, 26}, {27, SHIFT, 27}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 53}, {6, SHIFT, 68}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 24}, {18, SHIFT, 69}, },
			{{-1, ERROR, 57}, {3, SHIFT, 72}, {38, SHIFT, 73}, },
			{{-1, ERROR, 58}, {6, SHIFT, 74}, },
			{{-1, REDUCE, 16}, {7, SHIFT, 62}, {8, SHIFT, 63}, },
			{{-1, ERROR, 60}, {6, SHIFT, 75}, {7, SHIFT, 62}, {8, SHIFT, 63}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 62}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, ERROR, 63}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, ERROR, 64}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, ERROR, 65}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, ERROR, 66}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, ERROR, 67}, {6, SHIFT, 81}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 69}, {24, SHIFT, 24}, {25, SHIFT, 25}, {26, SHIFT, 26}, {27, SHIFT, 27}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 25}, {18, SHIFT, 69}, },
			{{-1, ERROR, 72}, {4, SHIFT, 84}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 50}, },
			{{-1, REDUCE, 43}, {9, SHIFT, 64}, {10, SHIFT, 65}, {11, SHIFT, 66}, },
			{{-1, REDUCE, 44}, {9, SHIFT, 64}, {10, SHIFT, 65}, {11, SHIFT, 66}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 48}, },
			{{-1, ERROR, 81}, {0, SHIFT, 45}, {5, SHIFT, 46}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 20}, {7, SHIFT, 62}, {8, SHIFT, 63}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 6}, },
			{{-1, 7}, {14, 21}, },
			{{-1, 8}, {13, 20}, {22, 20}, },
			{{-1, 9}, },
			{{-1, 10}, },
			{{-1, 35}, },
			{{-1, 28}, {17, 30}, {18, 31}, },
			{{-1, 52}, {16, 29}, {17, 29}, {18, 29}, },
			{{-1, 36}, {30, 39}, },
			{{-1, -1}, },
			{{-1, 11}, },
			{{-1, 12}, },
			{{-1, 53}, {42, 58}, {51, 67}, },
			{{-1, 54}, },
			{{-1, 55}, },
			{{-1, 70}, {71, 83}, },
			{{-1, 56}, {69, 82}, },
			{{-1, 57}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, 47}, {43, 59}, {46, 60}, {81, 85}, },
			{{-1, 48}, {62, 76}, {63, 77}, },
			{{-1, 49}, {64, 78}, {65, 79}, {66, 80}, },
			{{-1, 13}, {14, 22}, },
			{{-1, 14}, },
			{{-1, 71}, },
			{{-1, -1}, },
			{{-1, -1}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: '>>', 'var', 'const', 'funcao', 'procedimento'",
			"expecting: 'procedimento'",
			"expecting: ':'",
			"expecting: EOF",
			"expecting: '>>', 'funcao', 'procedimento', EOF",
			"expecting: 'inteiro', 'real', 'booleano', 'cadeia'",
			"expecting: id",
			"expecting: '[', id",
			"expecting: '('",
			"expecting: ';', '<<'",
			"expecting: ';'",
			"expecting: numero, '('",
			"expecting: '<<'",
			"expecting: ')', 'inteiro', 'real', 'booleano', 'cadeia'",
			"expecting: ';', ']', ')', '+', '-', '*', '/', '%', '>>', 'funcao', 'procedimento', EOF",
			"expecting: ']', '+', '-'",
			"expecting: ')'",
			"expecting: ')', '|'",
			"expecting: ';', '+', '-'",
			"expecting: ')', '+', '-'",
			"expecting: ']'",
			"expecting: '+', '-', '>>', 'funcao', 'procedimento', EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 2, 2, 2, 3, 0, 4, 0, 0, 4, 4, 4, 0, 2, 5, 5, 5, 6, 4, 0, 4, 6, 7, 7, 7, 7, 6, 7, 6, 6, 8, 8, 9, 10, 10, 11, 12, 10, 8, 13, 13, 11, 0, 14, 11, 15, 14, 14, 0, 13, 7, 16, 16, 16, 17, 7, 16, 18, 19, 6, 11, 11, 11, 11, 11, 16, 4, 5, 17, 17, 20, 17, 4, 14, 14, 14, 14, 14, 14, 11, 17, 17, 7, 21, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
