/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ATipoInteiroTipoBase extends PTipoBase
{
    private TTipoInteiro _tipoInteiro_;

    public ATipoInteiroTipoBase()
    {
        // Constructor
    }

    public ATipoInteiroTipoBase(
        @SuppressWarnings("hiding") TTipoInteiro _tipoInteiro_)
    {
        // Constructor
        setTipoInteiro(_tipoInteiro_);

    }

    @Override
    public Object clone()
    {
        return new ATipoInteiroTipoBase(
            cloneNode(this._tipoInteiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoInteiroTipoBase(this);
    }

    public TTipoInteiro getTipoInteiro()
    {
        return this._tipoInteiro_;
    }

    public void setTipoInteiro(TTipoInteiro node)
    {
        if(this._tipoInteiro_ != null)
        {
            this._tipoInteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoInteiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoInteiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoInteiro_ == child)
        {
            this._tipoInteiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoInteiro_ == oldChild)
        {
            setTipoInteiro((TTipoInteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
