/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ATipoParametroTipoParametro extends PTipoParametro
{
    private PTipoParametro _tipoParametro_;
    private TColEsq _colEsq_;
    private TColDir _colDir_;

    public ATipoParametroTipoParametro()
    {
        // Constructor
    }

    public ATipoParametroTipoParametro(
        @SuppressWarnings("hiding") PTipoParametro _tipoParametro_,
        @SuppressWarnings("hiding") TColEsq _colEsq_,
        @SuppressWarnings("hiding") TColDir _colDir_)
    {
        // Constructor
        setTipoParametro(_tipoParametro_);

        setColEsq(_colEsq_);

        setColDir(_colDir_);

    }

    @Override
    public Object clone()
    {
        return new ATipoParametroTipoParametro(
            cloneNode(this._tipoParametro_),
            cloneNode(this._colEsq_),
            cloneNode(this._colDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoParametroTipoParametro(this);
    }

    public PTipoParametro getTipoParametro()
    {
        return this._tipoParametro_;
    }

    public void setTipoParametro(PTipoParametro node)
    {
        if(this._tipoParametro_ != null)
        {
            this._tipoParametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoParametro_ = node;
    }

    public TColEsq getColEsq()
    {
        return this._colEsq_;
    }

    public void setColEsq(TColEsq node)
    {
        if(this._colEsq_ != null)
        {
            this._colEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colEsq_ = node;
    }

    public TColDir getColDir()
    {
        return this._colDir_;
    }

    public void setColDir(TColDir node)
    {
        if(this._colDir_ != null)
        {
            this._colDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoParametro_)
            + toString(this._colEsq_)
            + toString(this._colDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoParametro_ == child)
        {
            this._tipoParametro_ = null;
            return;
        }

        if(this._colEsq_ == child)
        {
            this._colEsq_ = null;
            return;
        }

        if(this._colDir_ == child)
        {
            this._colDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoParametro_ == oldChild)
        {
            setTipoParametro((PTipoParametro) newChild);
            return;
        }

        if(this._colEsq_ == oldChild)
        {
            setColEsq((TColEsq) newChild);
            return;
        }

        if(this._colDir_ == oldChild)
        {
            setColDir((TColDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
