/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoFechadaComando extends PComando
{
    private PDeclFechada _declFechada_;

    public ADeclaracaoFechadaComando()
    {
        // Constructor
    }

    public ADeclaracaoFechadaComando(
        @SuppressWarnings("hiding") PDeclFechada _declFechada_)
    {
        // Constructor
        setDeclFechada(_declFechada_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoFechadaComando(
            cloneNode(this._declFechada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoFechadaComando(this);
    }

    public PDeclFechada getDeclFechada()
    {
        return this._declFechada_;
    }

    public void setDeclFechada(PDeclFechada node)
    {
        if(this._declFechada_ != null)
        {
            this._declFechada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declFechada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declFechada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declFechada_ == child)
        {
            this._declFechada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declFechada_ == oldChild)
        {
            setDeclFechada((PDeclFechada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
