/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AExpSomaSubExp extends PExp
{
    private PExpSomaSub _expSomaSub_;

    public AExpSomaSubExp()
    {
        // Constructor
    }

    public AExpSomaSubExp(
        @SuppressWarnings("hiding") PExpSomaSub _expSomaSub_)
    {
        // Constructor
        setExpSomaSub(_expSomaSub_);

    }

    @Override
    public Object clone()
    {
        return new AExpSomaSubExp(
            cloneNode(this._expSomaSub_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpSomaSubExp(this);
    }

    public PExpSomaSub getExpSomaSub()
    {
        return this._expSomaSub_;
    }

    public void setExpSomaSub(PExpSomaSub node)
    {
        if(this._expSomaSub_ != null)
        {
            this._expSomaSub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSomaSub_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expSomaSub_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expSomaSub_ == child)
        {
            this._expSomaSub_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expSomaSub_ == oldChild)
        {
            setExpSomaSub((PExpSomaSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
