/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AListaExpListaExp extends PListaExp
{
    private PListaExpVazia _listaExpVazia_;

    public AListaExpListaExp()
    {
        // Constructor
    }

    public AListaExpListaExp(
        @SuppressWarnings("hiding") PListaExpVazia _listaExpVazia_)
    {
        // Constructor
        setListaExpVazia(_listaExpVazia_);

    }

    @Override
    public Object clone()
    {
        return new AListaExpListaExp(
            cloneNode(this._listaExpVazia_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaExpListaExp(this);
    }

    public PListaExpVazia getListaExpVazia()
    {
        return this._listaExpVazia_;
    }

    public void setListaExpVazia(PListaExpVazia node)
    {
        if(this._listaExpVazia_ != null)
        {
            this._listaExpVazia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaExpVazia_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaExpVazia_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaExpVazia_ == child)
        {
            this._listaExpVazia_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaExpVazia_ == oldChild)
        {
            setListaExpVazia((PListaExpVazia) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
