/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorExp extends PExp
{
    private PExp _exp_;
    private TMaiorQ _maiorQ_;
    private PExpSomaSub _expSomaSub_;

    public AMaiorExp()
    {
        // Constructor
    }

    public AMaiorExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMaiorQ _maiorQ_,
        @SuppressWarnings("hiding") PExpSomaSub _expSomaSub_)
    {
        // Constructor
        setExp(_exp_);

        setMaiorQ(_maiorQ_);

        setExpSomaSub(_expSomaSub_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorExp(
            cloneNode(this._exp_),
            cloneNode(this._maiorQ_),
            cloneNode(this._expSomaSub_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMaiorQ getMaiorQ()
    {
        return this._maiorQ_;
    }

    public void setMaiorQ(TMaiorQ node)
    {
        if(this._maiorQ_ != null)
        {
            this._maiorQ_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorQ_ = node;
    }

    public PExpSomaSub getExpSomaSub()
    {
        return this._expSomaSub_;
    }

    public void setExpSomaSub(PExpSomaSub node)
    {
        if(this._expSomaSub_ != null)
        {
            this._expSomaSub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expSomaSub_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._maiorQ_)
            + toString(this._expSomaSub_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._maiorQ_ == child)
        {
            this._maiorQ_ = null;
            return;
        }

        if(this._expSomaSub_ == child)
        {
            this._expSomaSub_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._maiorQ_ == oldChild)
        {
            setMaiorQ((TMaiorQ) newChild);
            return;
        }

        if(this._expSomaSub_ == oldChild)
        {
            setExpSomaSub((PExpSomaSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
