/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import java.util.*;
import analysis.*;
import sarapatel.analysis.Analysis;

@SuppressWarnings("nls")
public final class AParametroSeparadorParametro extends PParametroSeparadorParametro
{
    private PParametro _parametro_;
    private final LinkedList<PSeparadorParametro> _separadorParametro_ = new LinkedList<PSeparadorParametro>();

    public AParametroSeparadorParametro()
    {
        // Constructor
    }

    public AParametroSeparadorParametro(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _separadorParametro_)
    {
        // Constructor
        setParametro(_parametro_);

        setSeparadorParametro(_separadorParametro_);

    }

    @Override
    public Object clone()
    {
        return new AParametroSeparadorParametro(
            cloneNode(this._parametro_),
            cloneList(this._separadorParametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametroSeparadorParametro(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PSeparadorParametro> getSeparadorParametro()
    {
        return this._separadorParametro_;
    }

    public void setSeparadorParametro(List<?> list)
    {
        for(PSeparadorParametro e : this._separadorParametro_)
        {
            e.parent(null);
        }
        this._separadorParametro_.clear();

        for(Object obj_e : list)
        {
            PSeparadorParametro e = (PSeparadorParametro) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._separadorParametro_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._separadorParametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._separadorParametro_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PSeparadorParametro> i = this._separadorParametro_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PSeparadorParametro) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
