/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TFuncao extends Token
{
    public TFuncao()
    {
        super.setText("funcao");
    }

    public TFuncao(int line, int pos)
    {
        super.setText("funcao");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFuncao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFuncao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFuncao text.");
    }
}
