/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import analysis.*;
import sarapatel.analysis.Analysis;

@SuppressWarnings("nls")
public final class TIniBloco extends Token
{
    public TIniBloco()
    {
        super.setText("comece");
    }

    public TIniBloco(int line, int pos)
    {
        super.setText("comece");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIniBloco(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIniBloco(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIniBloco text.");
    }
}
